Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: kmsTestFunction.App
      CodeUri: C:\project\KmsTestFunction\HelloWorldFunction
      Runtime: java11